### ISSUE TITLE
Support puppetlabs/stdlib v9

### ISSUE THREAD

**Issue by xvilo** [cirrax/puppet-mollyguard#2]
We need to upgrade some dependencies, and as such, we need to support for puppetlabs/stdlib v9 for this module. I (personally) don't have a lot of experience yet with Puppet (modules). So I hope somebody could add support for it

**Comment by trefzer** [comment]
There are no restrictions I'm aware of. (besides the metadata.json file needs an update). Did you encounter any errors ?

**Comment by xvilo** [comment]
To this point I've not been able to install puppet project dependencies because of the mismatch. I can change the file, do the automations test enough to be sure of it?

**Comment by trefzer** [comment]
depends wich tests ! but I'm using this module already with stdlib 9.6 and it works. so probably yes.

**Comment by xvilo** [comment]
https://github.com/cirrax/puppet-mollyguard/pull/3
